version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'devjiwonchoi'
    groups:
      production:
        dependency-type: 'production'
      development:
        dependency-type: 'development'
